
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from './../components/SideBar';
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
                   ${process.env.NODE_ENV === 'development' ? 'debug-screens' : ''}
                   min-h-screen w-full bg-white text-black flex`}>
        
        {/* SideBar */}
        <aside className={"border"}>
          <SideBar />
        </aside>

        {/* Main */}
        <main className={"p-8 w-full"}>
          <Link href="/">Go to Dashboard</Link>
          
          <Link href="/users">Go to Users</Link>
          <Link href="/orders">Go to Orders</Link>
          <Link href="/settings">Go to Settings</Link>
          {children}
        </main>
                
      </body>
    </html>
  );
}
